name = "cf-worker-ws-dev"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "141.11.17.205:443"
UUID = "a084cf8b-5825-43a0-b202-7bf6752f70ee"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
